### ISSUE TITLE
Better error when image can't be found

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [CloudBindle/youxia#41]
Noticed a problem today with Niall: If you reference an image that can't be found, the stack trace coming back looks like it is talking about missing block device mappings, which is confusing.

Code:

```
    private List<BlockDeviceMapping> getBlockMappings() {
        // copy block mapping from image to new launch specification to ensure that devices make it through
        DescribeImagesRequest ir = new DescribeImagesRequest();
        ir.setImageIds(Lists.newArrayList(amiID));
        DescribeImagesResult describeImagesResult = ec2.describeImages(ir);
/*
Before attempting to get blockDeviceMappings, there should really be a check
that getImages() returned an array with something in it (rather than an empty non-null array),
and throw an exception with a useful message.
*/
        List<BlockDeviceMapping> blockDeviceMappings = describeImagesResult.getImages().get(0).getBlockDeviceMappings();
        // turn off encrypted flag, not sure why it might be specified for snapshots but it seems tto crash at runtime with
        // "Exception in thread "main" java.lang.RuntimeException: com.amazonaws.AmazonServiceException: Parameter encrypted is invalid. You cannot specify the encrypted flag if specifying a snapshot id in a block device mapping."
        for (BlockDeviceMapping mapping : blockDeviceMappings) {
            if (mapping.getEbs() != null) {
                mapping.getEbs().setEncrypted(null);
            }
        }
        return blockDeviceMappings;
    }
```

Line:
https://github.com/CloudBindle/youxia/blob/4b921e975f512401f8aebeb4394d2427b28b16ad/youxia-deployer/src/main/java/io/cloudbindle/youxia/amazonaws/Requests.java#L233

**Comment by denis-yuen** [comment]
I can't re-produce this. 
If the ami id is incorrect, the message coming back is pretty obvious (and different)

```
Exception in thread "main" java.lang.RuntimeException: com.amazonaws.AmazonServiceException: The image id '[ami-4d883351]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: bb0a22a7-469e-43b7-9fb6-a29f96732f0d)
    at io.cloudbindle.youxia.deployer.Deployer.requestAWSInstances(Deployer.java:364)
    at io.cloudbindle.youxia.deployer.Deployer.runDeployment(Deployer.java:604)
    at io.cloudbindle.youxia.deployer.Deployer.main(Deployer.java:655)
Caused by: com.amazonaws.AmazonServiceException: The image id '[ami-4d883351]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: bb0a22a7-469e-43b7-9fb6-a29f96732f0d)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1077)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:725)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
    at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:9393)
    at com.amazonaws.services.ec2.AmazonEC2Client.describeImages(AmazonEC2Client.java:4762)
    at io.cloudbindle.youxia.amazonaws.Requests.getBlockMappings(Requests.java:232)
    at io.cloudbindle.youxia.amazonaws.Requests.launchOnDemand(Requests.java:257)
    at io.cloudbindle.youxia.deployer.Deployer.launchOnDemandInstances(Deployer.java:385)
    at io.cloudbindle.youxia.deployer.Deployer.requestAWSInstances(Deployer.java:282)
    ... 2 more
```

It should never get as far as looking at block mappings.

**Comment by denis-yuen** [comment]
Current working theory, some bizarre permissions thing. When we put in an incorrect image id, we get back the above message. This only occurs when hitting a correct image but also occurs for all images that Niall has access to.
