### ISSUE TITLE
Reaping failed nodes does not work in Azure

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [CloudBindle/youxia#45]
Reaping failed nodes in Azure fails with a stack trace that looks like this:

```
20:38:11.219 [pool-1-thread-3] ERROR i.p.a.c.ContainerProvisionerThreads - Youxia reaper threw the following exception
com.amazonaws.AmazonServiceException: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'N/A/20150928/eu-west-1/ec2/aws4_request,' (Service: Amaz
onEC2; Status Code: 401; Error Code: AuthFailure; Request ID: 525abda8-845b-41ab-87b6-a37cdc0e87e4)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1077) ~[pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:725) ~[pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460) ~[pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295) ~[pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:9393) ~[pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at com.amazonaws.services.ec2.AmazonEC2Client.describeRegions(AmazonEC2Client.java:1308) ~[pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at com.amazonaws.services.ec2.AmazonEC2Client.describeRegions(AmazonEC2Client.java:8166) ~[pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at io.cloudbindle.youxia.reaper.Reaper.<init>(Reaper.java:150) ~[pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at io.cloudbindle.youxia.reaper.Reaper.main(Reaper.java:484) ~[pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at info.pancancer.arch3.containerProvisioner.ContainerProvisionerThreads.runReaper(ContainerProvisionerThreads.java:389) [pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at info.pancancer.arch3.containerProvisioner.ContainerProvisionerThreads.access$000(ContainerProvisionerThreads.java:46) [pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at info.pancancer.arch3.containerProvisioner.ContainerProvisionerThreads$CleanupVMs.call(ContainerProvisionerThreads.java:317) [pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at info.pancancer.arch3.containerProvisioner.ContainerProvisionerThreads$CleanupVMs.call(ContainerProvisionerThreads.java:254) [pancancer-arch-3-1.1-beta.4.jar:1.1-beta.4]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

I'm guessing that somewhere there is a call to the Reaper that is missing `--azure`. This is happening in a Pancancer Launcher. The reaper config is: `youxia_reaper_params=--test --azure` and the youxia_deployer_parameters also have `--azure` as the suffix.

**Comment by denis-yuen** [comment]
You have a typo there, it should be`youxia_reaper_parameters`, not `youxia_deployer_params`

I think there was a previous ticket on this, but I can't find it

**Comment by SolomonShorser-OICR** [comment]
Hmm yup, looks like you're right.
